uniform float2 screen_size;

#define BUFFER_SCREEN_SIZE screen_size
#define BUFFER_WIDTH  BUFFER_SCREEN_SIZE.x
#define BUFFER_HEIGHT BUFFER_SCREEN_SIZE.y
#define BUFFER_ASPECT_RATIO (BUFFER_WIDTH / BUFFER_HEIGHT)
#define BUFFER_RCP_WIDTH  (1.0 / BUFFER_WIDTH)
#define BUFFER_RCP_HEIGHT (1.0 / BUFFER_HEIGHT)
#define BUFFER_PIXEL_SIZE float2(BUFFER_RCP_WIDTH, BUFFER_RCP_HEIGHT)
